[project]
name = "por-deltae-lib"
version = "0.1.0"
description = "PoR・ΔE OSS reference implementation"
authors = [
  { name = "Yuu6798", email = "kkoo6798@gmail.com" },
]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["sentence-transformers>=0.12.0"]

[tool.mypy]
strict = true
warn_unused_ignores = true
disallow_any_generics = true
disallow_any_untyped_defs = true
no_implicit_optional = true

[tool.ruff]
line-length = 100
extend-select = ["PGH"]
extend-ignore = ["ANN101"]
