[tool.poetry]
name        = "por-deltae-lib"
version     = "0.1.0"
description = "PoR / Î”E / grv metrics library"
authors     = ["Yuu6798 <mail@example.com>"]

[[tool.poetry.packages]]
include = "ugh3_metrics_lib"
from    = "src"


[tool.poetry.group.dev.dependencies]
pytest = "<8.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_ignores = true
disallow_any_generics = true
disallow_any_untyped_defs = true
no_implicit_optional = true

[tool.ruff]
line-length = 100
extend-select = ["PGH"]
extend-ignore = ["ANN101"]
