[tool.poetry]
name        = "por-deltae-lib"
version     = "0.1.0"
description = "PoR / Î”E / grv metrics library"
authors     = ["Yuu6798 <mail@example.com>"]

[[tool.poetry.packages]]
include = "ugh3_metrics_lib"
from    = "src"


[tool.poetry.group.dev.dependencies]
pytest = "7.4.4"
matplotlib = "^3.10.3"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_ignores = true
disallow_any_generics = true
disallow_any_untyped_defs = true
no_implicit_optional = true

[tool.ruff]
line-length = 100
extend-select = ["PGH"]
extend-ignore = ["ANN101"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"

[[tool.poetry.packages]]
include = "phase_map_demo"
from = "src"

[[tool.poetry.packages]]
include = "facade"
from = "src"

[[tool.poetry.packages]]
include = "core"
from = "src"

[[tool.poetry.packages]]
include = "secl"
from = "src"

[[tool.poetry.packages]]
include = "phase_map_demo"
from = "src"

[tool.poetry.scripts]
phase-map-demo = "phase_map_demo.app:main"
